# Generated by Django 6.0.7 on 2026-07-27 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useretude',
            name='etude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='studies.etude'),
        ),
        migrations.AddField(
            model_name='useretude',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etude_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='useretude',
            unique_together={('user', 'etude')},
        ),
    ]
