# Generated by Django 6.0.7 on 2026-07-27 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_id', models.CharField(max_length=50, unique=True, verbose_name='Numéro patient')),
                ('genre', models.CharField(blank=True, max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('age_grp', models.CharField(blank=True, max_length=1)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Etude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=300, verbose_name="Nom de l'étude")),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('paused', 'En pause'), ('completed', 'Terminée')], default='draft', max_length=20)),
                ('periodes', models.JSONField(blank=True, default=list, help_text='[{"key": "T1", "label": "Baseline", "order": 1}, ...]')),
                ('scoring_rules', models.JSONField(blank=True, default=dict, help_text='Configuration des scores calculés automatiquement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudes_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étude',
                'verbose_name_plural': 'Études',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientEtude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_etude', models.CharField(blank=True, max_length=50, verbose_name="Numéro dans l'étude")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_etudes', to='studies.etude')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_etudes', to='studies.patient')),
            ],
            options={
                'verbose_name': 'Patient-Étude',
                'verbose_name_plural': 'Patients-Études',
                'unique_together': {('patient', 'etude')},
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='etudes',
            field=models.ManyToManyField(related_name='patients', through='studies.PatientEtude', to='studies.etude'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='Code section')),
                ('title_fr', models.CharField(max_length=300, verbose_name='Titre (FR)')),
                ('title_mg', models.CharField(blank=True, max_length=300, verbose_name='Titre (MG)')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='studies.etude')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order'],
                'unique_together': {('etude', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Clé technique')),
                ('type', models.CharField(choices=[('text', 'Texte libre'), ('integer', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('date', 'Date'), ('select_one', 'Choix unique'), ('select_multiple', 'Choix multiple'), ('note', 'Note / Information')], max_length=20)),
                ('label_fr', models.CharField(max_length=500, verbose_name='Label (FR)')),
                ('label_mg', models.CharField(blank=True, max_length=500, verbose_name='Label (MG)')),
                ('hint_fr', models.CharField(blank=True, max_length=300)),
                ('hint_mg', models.CharField(blank=True, max_length=300)),
                ('required', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('choices', models.JSONField(blank=True, default=list, help_text='[{"value": "1", "fr": "Oui", "mg": "Eny"}, ...]')),
                ('constraint', models.JSONField(blank=True, default=dict, help_text='{"min": 0, "max": 100, "regex": "^[0-9]+$"}')),
                ('relevant', models.JSONField(blank=True, default=dict, help_text='{"eq": ["question_name", "value"]}')),
                ('spss_name', models.CharField(blank=True, max_length=8, verbose_name='Nom SPSS')),
                ('spss_label', models.CharField(blank=True, max_length=200, verbose_name='Label SPSS')),
                ('score_key', models.CharField(blank=True, max_length=50, verbose_name='Clé de correction')),
                ('score_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='studies.section')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order'],
                'unique_together': {('section', 'name')},
            },
        ),
    ]
