# Generated by Django 6.0.7 on 2026-07-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='etudes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score_key',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score_value',
        ),
        migrations.AddField(
            model_name='etude',
            name='auto_calculs',
            field=models.JSONField(blank=True, default=list, help_text='["age", "imc", "age_grp"]'),
        ),
        migrations.AddField(
            model_name='etude',
            name='choice_lists',
            field=models.JSONField(blank=True, default=dict, help_text='{"genre": [{"value": "1", "fr": "Masculin", "mg": "Lahy"}]}'),
        ),
        migrations.AddField(
            model_name='etude',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text="Configuration générale de l'étude"),
        ),
        migrations.AddField(
            model_name='etude',
            name='domaine',
            field=models.CharField(choices=[('diabète', 'Diabète'), ('paludisme', 'Paludisme'), ('vih', 'VIH/SIDA'), ('maternité', 'Maternité'), ('nutrition', 'Nutrition'), ('cardiologie', 'Cardiologie'), ('psychiatrie', 'Psychiatrie'), ('epidemiologie', 'Épidémiologie'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='patientetude',
            name='statut',
            field=models.CharField(default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='hint_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='label_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Label (EN)'),
        ),
        migrations.AddField(
            model_name='question',
            name='score_correct',
            field=models.JSONField(blank=True, default=list, help_text='Réponses correctes: ["1", "3"] ou "1"'),
        ),
        migrations.AddField(
            model_name='question',
            name='score_points',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Titre (EN)'),
        ),
        migrations.AlterField(
            model_name='etude',
            name='scoring_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Règles de calcul des scores'),
        ),
        migrations.AlterField(
            model_name='question',
            name='constraint',
            field=models.JSONField(blank=True, default=dict, help_text='{"min": 0, "max": 100, "regex": "^[0-9]+$", "msgFr": "Erreur"}'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Texte libre'), ('integer', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('date', 'Date'), ('datetime', 'Date + Heure'), ('time', 'Heure'), ('select_one', 'Choix unique'), ('select_multiple', 'Choix multiple'), ('likert', 'Échelle de Likert'), ('gps', 'GPS'), ('photo', 'Photo'), ('video', 'Vidéo'), ('audio', 'Audio'), ('signature', 'Signature'), ('barcode', 'Code-barres'), ('note', 'Note / Information')], max_length=20),
        ),
    ]
