# Generated by Django 6.0.7 on 2026-07-27 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reponse',
            name='auto_calculs',
            field=models.JSONField(blank=True, default=dict, verbose_name='Calculs auto'),
        ),
        migrations.AddField(
            model_name='reponse',
            name='device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reponse',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reponse',
            name='gps_lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reponse',
            name='statut',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='reponse',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('export', 'Export'), ('login', 'Connexion'), ('sync', 'Synchronisation')], max_length=20),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('audio', 'Audio'), ('video', 'Vidéo'), ('signature', 'Signature')], max_length=20)),
                ('fichier', models.FileField(upload_to='media/%Y/%m/%d/')),
                ('taille', models.IntegerField(default=0, verbose_name='Taille en bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='surveys.reponse')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
            },
        ),
    ]
